version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wordpress_boilerplate_app
    restart: always
    ports:
      - "80:80"
    command: sleep infinity  
    volumes:
      - ../:/var/www/html
      - ~/.ssh:/home/vscode/.ssh:cached
      - ~/.gitconfig:/home/vscode/.gitconfig:cached
      - ./nginx:/etc/nginx/sites-available
      - ./logs/:/var/log/nginx
    depends_on:
      - database
    networks:
      - app-network

  database:
    image: mysql:8.0.34
    container_name: wordpress_boilerplate_database
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/wordpress.sql:/docker-entrypoint-initdb.d/wordpress.sql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: wordpress_boilerplate_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    env_file:
      - .env
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - database
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
